{{- if and .Values.hcloudToken (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hetzner-firewall-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hetzner-firewall-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  HCLOUD_TOKEN: {{ .Values.hcloudToken | quote }}
{{- end }}
